"""Generate REPRODUCE.md from stages.py and expected.json.

The stage graph is the source of truth; the document is its output.
English and mechanical on purpose — commands, inputs, outputs, and the
number each stage produces. Rationale lives in docs/, not here.

    python3 repro/report.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from stages import STAGES, RAW_DOI, CELLS   # noqa: E402

TIER_NAME = {1: 'raw to cache', 2: 'characterisation tables',
             3: 'labels and training data', 4: 'training',
             5: 'evaluation', 6: 'board'}


def main():
    spec = json.load(open(os.path.join(HERE, 'expected.json'),
                          encoding='utf-8'))
    L = []
    w = L.append

    w('# Reproduce\n')
    w('Generated by `repro/report.py` from `repro/stages.py`. '
      'Do not edit by hand.\n')

    ac = spec['adopted_config']
    w('## Adopted configuration\n')
    w(f"- Trim: **{ac['trim'].split('(')[0].strip()}** "
      f"({ac['trim'].split('(', 1)[1].rstrip(')') if '(' in ac['trim'] else ''})")
    w(f"- History aggregation: `--trim-agg {ac['trim_agg']}`")
    w(f"- Exceedance tolerance: discharge {ac['tolerance_A']['discharge']} A, "
      f"charge {ac['tolerance_A']['charge']} A\n")

    w('## Sources\n')
    w('| Name | DOI |')
    w('|---|---|')
    for k, (doi, _) in RAW_DOI.items():
        w(f'| {k} | `{doi}` |')
    w('\nUnpack into `raw/<name>/`. See `DATA.md`.\n')

    w('## Stages\n')
    w('Run with `python3 repro/run.py <id>`; upstream stages run first.\n')
    tot = 0
    for tier in sorted({s['tier'] for s in STAGES}):
        w(f'### tier {tier} — {TIER_NAME.get(tier, "")}\n')
        w('| id | min | command | outputs |')
        w('|---|---:|---|---|')
        for s in [x for x in STAGES if x['tier'] == tier]:
            tot += s['minutes']
            m = f"{s['minutes']}" + ('' if s.get('measured') else '~')
            if s.get('board'):
                m += ' (board)'
            cmd = s['cmd'].replace('{py}', 'python3').replace('\n', ' ')
            n = len(s['outputs'])
            out = s['outputs'][0] + (f' +{n - 1}' if n > 1 else '')
            w(f"| `{s['id']}` | {m} | `{cmd}` | `{out}` |")
        w('')
    meas = sum(x['minutes'] for x in STAGES if x.get('measured'))
    w(f'Full rebuild: {tot} minutes ({tot / 60:.1f} h) if every stage takes '
      f'the time recorded against it. `~` marks an estimate that was never '
      f'timed, and those account for {tot - meas} of those minutes '
      f'({(tot - meas) / tot * 100:.0f} %) — so treat the total as a '
      f'planning figure, not a measurement. Measured stages sum to {meas} '
      f'minutes ({meas / 60:.1f} h).\n')

    w('## Published numbers\n')
    w('`python3 repro/verify.py` recomputes each of these from the tables. '
      'A mismatch means the paper is wrong, not the table.\n')
    w('| id | value | table | section |')
    w('|---|---:|---|---|')
    for c in spec['checks']:
        src = c['source'].split('—')[0].strip()
        w(f"| `{c['id']}` | {c['value']} | `{c['table']}` | {src} |")
    w('')

    w('## Cells and evaluation protocol\n')
    w(', '.join(f'`{c}`' for c in CELLS) + '\n')
    w('The three arms are NOT evaluated the same way, and a single sentence '
      'about all three would be wrong about one of them.\n')
    w('| arm | protocol | what a number from it means |')
    w('|---|---|---|')
    w('| SOP | leave-one-cell-out | the evaluated cell trains no model and '
      'calibrates no safety factor |')
    w('| SOH | leave-one-cell-out | same, over the same six folds |')
    w('| SOC | **per-cell calibrated, not held out** | every filter reads '
      'its own cell\'s characterisation surface, so the spread is over '
      'operating conditions within a cell and says nothing about transfer '
      'to an unseen cell |')
    w('')
    w('One more thing the fold names hide: the dataset runs one physical '
      'cell per aging protocol, so holding out a cell holds out its '
      'protocol too. That makes the held-out test harder than cell '
      'variation alone, and it means no result here can attribute a '
      'difference to cell or to protocol separately. `CC` and `CC_CELL2` '
      'are the only same-protocol pair. `manifests/generalization_scope.yaml`'
      ' holds both axes at PARTIAL for this reason.\n')
    w('What ships is neither protocol: the board carries an all-cell fit, '
      'because a product must not be a model trained without one of its own '
      'six cells. Leave-one-cell-out measures the cost of generalising; it '
      'is not the artifact.\n')

    w('## Not on the critical path\n')
    w('`python3 repro/run.py --exploratory` lists the remaining scripts '
      'and why each is excluded.\n')

    out = os.path.join(ROOT, 'REPRODUCE.md')
    open(out, 'w', encoding='utf-8').write('\n'.join(L))
    print(f'  -> {out}  ({len(L)} lines)')


if __name__ == '__main__':
    main()
