"""Generate REPRODUCE.md from stages.py and expected.json.

The stage graph is the source of truth; the document is its output.
English and mechanical on purpose — commands, inputs, outputs, and the
number each stage produces. Rationale lives in docs/, not here.

    python3 repro/report.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from stages import STAGES, EXPLORATORY, RAW_DOI, CELLS   # noqa: E402

TIER_NAME = {1: 'raw to cache', 2: 'characterisation tables',
             3: 'labels and training data', 4: 'training',
             5: 'evaluation', 6: 'board'}


def main():
    spec = json.load(open(os.path.join(HERE, 'expected.json'),
                          encoding='utf-8'))
    L = []
    w = L.append

    w('# Reproduce\n')
    w('Generated by `repro/report.py` from `repro/stages.py`. '
      'Do not edit by hand.\n')

    ac = spec['adopted_config']
    w('## Adopted configuration\n')
    w(f"- Trim: **{ac['trim'].split('(')[0].strip()}** "
      f"({ac['trim'].split('(', 1)[1].rstrip(')') if '(' in ac['trim'] else ''})")
    w(f"- History aggregation: `--trim-agg {ac['trim_agg']}`")
    w(f"- Exceedance tolerance: discharge {ac['tolerance_A']['discharge']} A, "
      f"charge {ac['tolerance_A']['charge']} A\n")

    w('## Sources\n')
    w('| Name | DOI |')
    w('|---|---|')
    for k, (doi, _) in RAW_DOI.items():
        w(f'| {k} | `{doi}` |')
    w('\nUnpack into `raw/<name>/`. See `DATA.md`.\n')

    w('## Stages\n')
    w('Run with `python3 repro/run.py <id>`; upstream stages run first.\n')
    tot = 0
    for tier in sorted({s['tier'] for s in STAGES}):
        w(f'### tier {tier} — {TIER_NAME.get(tier, "")}\n')
        w('| id | min | command | outputs |')
        w('|---|---:|---|---|')
        for s in [x for x in STAGES if x['tier'] == tier]:
            tot += s['minutes']
            m = f"{s['minutes']}" + ('' if s.get('measured') else '~')
            if s.get('board'):
                m += ' (board)'
            cmd = s['cmd'].replace('{py}', 'python3').replace('\n', ' ')
            n = len(s['outputs'])
            out = s['outputs'][0] + (f' +{n - 1}' if n > 1 else '')
            w(f"| `{s['id']}` | {m} | `{cmd}` | `{out}` |")
        w('')
    w(f'Full rebuild: about {tot} minutes ({tot / 60:.0f} h). '
      '`~` marks an estimate that was never timed.\n')

    w('## Published numbers\n')
    w('`python3 repro/verify.py` recomputes each of these from the tables. '
      'A mismatch means the paper is wrong, not the table.\n')
    w('| id | value | table | section |')
    w('|---|---:|---|---|')
    for c in spec['checks']:
        src = c['source'].split('—')[0].strip()
        w(f"| `{c['id']}` | {c['value']} | `{c['table']}` | {src} |")
    w('')

    w('## Cells\n')
    w(', '.join(f'`{c}`' for c in CELLS) + '\n')
    w('Leave-one-cell-out everywhere: the evaluated cell trains no model '
      'and calibrates no safety factor.\n')

    w('## Not on the critical path\n')
    w('`python3 repro/run.py --exploratory` lists the remaining scripts '
      'and why each is excluded.\n')

    out = os.path.join(ROOT, 'REPRODUCE.md')
    open(out, 'w', encoding='utf-8').write('\n'.join(L))
    print(f'  -> {out}  ({len(L)} lines)')


if __name__ == '__main__':
    main()
