"""Emit mcu/soh_tables.h for the ridge SOH model.

Deliberately drop-in: it defines the same SOH_NIN and the same soh_mu/soh_sd
arrays the CNN header defined, so soh_core.c standardises identically and only
the inference body changes.  SOH_RIDGE tells soh_core.c which body to compile.

Refuses to ship a leave-one-cell-out fold for the same reason
export_mcu_tables.py does: a header that goes on a board must be the all-cell
fit, or the product is a model trained without one of its own cells.
"""
from __future__ import annotations

import argparse
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))


def carr(name, a, per=8):
    f = np.asarray(a, np.float64).ravel()
    s = [f"static const float {name}[{f.size}] = {{"]
    for i in range(0, f.size, per):
        s.append("  " + ", ".join(f"{float(x):.9g}f" for x in f[i:i + per])
                 + ",")
    s.append("};")
    return "\n".join(s)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-dir", default=os.path.join(HERE, "runs_soh_ridge"))
    ap.add_argument("--holdout", default="ALL",
                    help="which fit to export.  Anything but ALL needs "
                         "--allow-fold and is a benchmark artifact, not a "
                         "deployable header.")
    ap.add_argument("--allow-fold", action="store_true")
    ap.add_argument("--out", default=os.path.join(HERE, "..", "mcu",
                                                  "soh_tables.h"))
    a = ap.parse_args()

    if a.holdout != "ALL" and not a.allow_fold:
        raise SystemExit(
            f"  --holdout {a.holdout} is a leave-one-cell-out fold: the model "
            f"fitted without {a.holdout}.  Exporting it as the header that "
            f"ships would put a model trained without one of the six cells on "
            f"the board.  Pass --allow-fold if you really mean to measure a "
            f"fold, or run soh_ridge.py --deployment to make the all-cell fit.")

    p = os.path.join(a.run_dir, f"soh_{a.holdout}.npz")
    if not os.path.exists(p):
        raise SystemExit(
            f"  {os.path.relpath(p, HERE)} does not exist.  Run\n"
            f"    python3 soh_ridge.py --save-model runs_soh_ridge "
            f"--save-pred results/soh_pred.npz --deployment")
    ck = np.load(p, allow_pickle=True)
    w, b = np.asarray(ck["w"], float), float(ck["b"])
    mu, sd = np.asarray(ck["mu"], float), np.asarray(ck["sd"], float)
    n_in = int(ck["n_in"])
    if not (w.shape == mu.shape == sd.shape == (n_in,)):
        raise SystemExit(f"  shape mismatch: w{w.shape} mu{mu.shape} "
                         f"sd{sd.shape} n_in={n_in}")
    tot = (w.size + mu.size + sd.size + 1) * 4

    os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write(f"""/* Generated by analysis/export_soh_ridge.py.  Do not edit by hand.
 *
 * SOH from the dQ/dV curve, ridge on the standardised 64-point input:
 *
 *     soh = b + sum_i w_i * (x_i - mu_i) / sd_i
 *
 * Fit: {str(ck['holdout'])}, alpha {float(ck['alpha']):g}.  {w.size + 1} coefficients
 * ({w.size} weights + 1 intercept) against the CNN's 10,945 parameters per
 * seed, three seeds.  Weights {tot / 1024:.1f} KB.
 *
 * The CNN this replaces was never chosen by a procedure that had not already
 * seen the held-out cells: in nested selection it scored worst of every
 * candidate family on every fold.  See spec 36.
 */
#ifndef SOH_TABLES_H
#define SOH_TABLES_H

#include <stdint.h>

#define SOH_RIDGE 1
#define SOH_NIN {n_in}
#define SOH_NSEED 1
#define SOH_B ({b:.9g}f)

{carr('soh_mu', mu)}

{carr('soh_sd', sd)}

{carr('soh_w', w)}

#endif /* SOH_TABLES_H */
""")
    print(f"  {os.path.relpath(os.path.abspath(a.out), os.path.dirname(HERE))}")
    print(f"  fit {str(ck['holdout'])}, alpha {float(ck['alpha']):g}, "
          f"{w.size + 1} coefficients, {tot / 1024:.1f} KB "
          f"(CNN header was 33.0 KB of weights)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
